name = "temple-square-app"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "e4e4f001e0358d00af009eb7db7d89a4"
workers_dev = true

[[routes]]
pattern = "app.templesquare.dev"
custom_domain = true

[vars]
BACKEND_URL = "https://deep-search-REPLACE.a.run.app"
